### ISSUE TITLE
Passing invalid value in from-asid header

### ISSUE THREAD

**Issue by sonalnegivarma** [nhsconnect/integration-adaptor-mhs#13]
Description: This is a negative test. It will verify Asynchronous Reliable response with passing invalid from-asid in header value.
Test Data: 
Content-Type: application/json
Interaction-Id :"REPC_IN150016UK05"
sync-async : true
from-asid :invalid_asid123
Expected result: either 400 bad request or 500 internal server error
Actual Response - we are getting 200 OK with response body
Note: when we are changing header value for sync-async ="True" (Capital "T") instead of passing "true"(small "t"), 
 in this case we are getting 202 Accepted response.

**Comment by michael-kainos** [comment]
@sonalnegivarma this header is optional for the async requests, please retry for synchronous only in the latest release.

**Comment by sonalnegivarma** [comment]
@michael-kainos  Retested this defect. It is reproducible at my end - 

Test Data:
Content-Type: application/json
Interaction-Id :"REPC_IN150016UK05"
sync-async : true
from-asid :invalid_asid123
Expected result: either 400 bad request.
Actual Response - we are getting 200 OK with response body
Note: Previously when we are changing header value for sync-async ="True" (Capital "T") instead of passing "true"(small "t"), in this case we are getting 202 Accepted response.

But now, in both the cases it is giving 200 OK response.

@michael-kainos  Could you please look into this. I have added screenshot in JIRA ticket as well - 
https://medicaldirector.atlassian.net/browse/NHST-107

**Comment by michael-kainos** [comment]
@sonalnegivarma 
I have investigated and this is the expected response for all requests as the header is not required.

for the async reliable request, the 3rd and 4th 'extension 'nodes in the xml body is where the ASID can be updated and tested.

Please retry with this information and ignore the header

**Comment by sonalnegivarma** [comment]
@michael-kainos  
We are assuming that when sync-async is true we need to pass the from-asid in the header key.
Reference - https://medicaldirector.atlassian.net/wiki/spaces/NHS/pages/728400908/MHS+adaptor+functional+tests+plan

**Comment by InnaBerkovsky** [comment]
Hi @michael-kainos,

Looks like there is some misunderstanding here about synchronous request:

according to the documentation when setting sync-async = true, the request is synchronous. 
I'll tag you in where it was mentioned.

**Comment by sonalnegivarma** [comment]
Hey @michael-kainos  Thanks for confirming this. I have retested this defect.
Test data -  
Content-Type: application/json
Interaction-Id :"REPC_IN150016UK05"
wait-for-response : true
Expected result: 200 OK
Actual Response - 200 OK

Additional details and Screenshot has been added to JIRA ticket - https://medicaldirector.atlassian.net/browse/NHST-107
