### ISSUE TITLE
Synchronous message response returned in unexpected SOAP envelope

### ISSUE THREAD

**Issue by davesmith9088** [nhsconnect/integration-adaptor-mhs#21]
When using synchronous messaging (example request file attached to this issue) the response is returned 
as a SOAP response, which seems incorrect as the API does not take a SOAP request.

If we use an async message (request attached) with the wait-for-response header set to true, 
then we just get the response XML without the SOAP envelope (as expected)

Looks like a bug as types of payload we are getting back are inconsistent and seem to depend on the interaction type.

The issue can be recreated by sending the message payload in the example "MHS sync request.txt" file via CURL or postman.
This is for OpenTest, the ASID will need to be changed according to your Open Test connection details.

[MHS async request.txt](https://github.com/nhsconnect/integration-adaptor-mhs/files/4864486/MHS.async.request.txt)
[MHS async response.txt](https://github.com/nhsconnect/integration-adaptor-mhs/files/4864487/MHS.async.response.txt)
[MHS sync request.txt](https://github.com/nhsconnect/integration-adaptor-mhs/files/4864488/MHS.sync.request.txt)
[MHS sync response.txt](https://github.com/nhsconnect/integration-adaptor-mhs/files/4864489/MHS.sync.response.txt)

**Comment by petervdm** [comment]
Thanks for reporting this @davesmith9088, we'll add a ticket for it and get it looked at

**Comment by bartek-sarul** [comment]
NIAD ticket https://gpitbjss.atlassian.net/browse/NIAD-411
